### ISSUE TITLE
Datbase Creation

### ISSUE THREAD

**Issue by DakelNL** [DakelNL/companion_forms#1]
Somehow the database isn't created on activation

**Comment by DakelNL** [comment]
I figured out what the problem is, he doenst call the function on activation, or anytime else...

**Comment by DakelNL** [comment]
Update: The function for this won't run on activation, this is why it doesn't work!

**Comment by nielsdoorn** [comment]
Think I fixed it:

https://github.com/DakelNL/companion_forms/pull/18
